export const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";
const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";
const REQUEST_ADD_TO_CART = "REQUEST_ADD_TO_CART";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_SAVE_SHIPPING = "CART_SAVE_SHIPPING";
export const ENTER_PAYMENT_METHOD = ":ENTER_PAYMENT_METHOD";
