export default {
  products: [
    {
      image: "/images/d1.jpeg",
      name: "slim short",
      price: "80",
      brand: "nake",
      rating: "10",
      _id: "1",
    },
    {
      image: "/images/d1.jpeg",
      name: "slim short",
      price: "80",
      brand: "nake",
      rating: "10",
      _id: "2",
    },
    {
      image: "/images/d1.jpeg",
      name: "slim short",
      price: "80",
      brand: "nake",
      rating: "10",
      _id: "3",
    },
    {
      image: "/images/d1.jpeg",
      name: "slim short",
      price: "80",
      brand: "nake",
      rating: "10",
      _id: "4",
    },
    {
      image: "/images/d1.jpeg",
      name: "slim short",
      price: "80",
      brand: "nake",
      rating: "10",
      _id: "5",
    },
    {
      image: "/images/d1.jpeg",
      name: "slim short",
      price: "80",
      brand: "nake",
      rating: "10",
      id: "6",
    },
    {
      image: "/images/d1.jpeg",
      name: "slim short",
      price: "80",
      brand: "nake",
      rating: "10",
      _id: "7",
    },
    {
      image: "/images/d1.jpeg",
      name: "slim short",
      price: "80",
      brand: "nake",
      rating: "10",
      _id: "8",
    },
    {
      image: "/images/d1.jpeg",
      name: "slim short",
      price: "80",
      brand: "nake",
      rating: "10",
      _id: "9",
    },
    {
      image: "/images/d1.jpeg",
      name: "slim short",
      price: "80",
      brand: "nake",
      rating: "10",
      _id: "10",
    },
  ],
};
